services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      DATABASE_URL: "postgresql://gdlp:gdlp_pass@postgres:5432/gdlp_dev"
      NEXT_PUBLIC_MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    depends_on:
      - postgres
      - minio
    networks:
      - gdlp-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: gdlp
      POSTGRES_PASSWORD: gdlp_pass
      POSTGRES_DB: gdlp_dev
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - gdlp-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - dev-minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - gdlp-network

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - gdlp-network

volumes:
  dev-db-data:
  dev-minio-data:

networks:
  gdlp-network:
    driver: bridge
